name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Deploy to Database
        run: |
          echo "Connecting to Database with Password"
          mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DATABASE_PASSWORD }} -e "SELECT 1"
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


